#!/usr/bin/env python3
"""
Setup script for configuring Skynet with a remote PostgreSQL database.

Usage:
    python scripts/setup_postgres.py --url postgresql://user:pass@host:5432/dbname
    python scripts/setup_postgres.py --host db.example.com --port 5432 --user myuser --password mypass --dbname skynet

This script:
1. Tests the PostgreSQL connection
2. Creates all required tables if they don't exist
3. Generates the .env configuration for the service
"""

import argparse
import sys


def build_url(args) -> str:
    """Build a PostgreSQL connection URL from CLI arguments.

    Args:
        args: Parsed argparse namespace with url, host, port, user,
            password, and dbname attributes.

    Returns:
        A PostgreSQL connection URL string.
    """
    if args.url:
        return args.url
    if not all([args.host, args.user, args.password, args.dbname]):
        print("Error: provide --url or all of --host --user --password --dbname")
        sys.exit(1)
    port = args.port or 5432
    return f"postgresql://{args.user}:{args.password}@{args.host}:{port}/{args.dbname}"


def test_connection(url: str) -> bool:
    """Test connectivity to a PostgreSQL database.

    Args:
        url: PostgreSQL connection URL.

    Returns:
        True if the connection succeeds, False otherwise.
    """
    try:
        from sqlalchemy import create_engine, text

        engine = create_engine(url, echo=False, pool_pre_ping=True)
        with engine.connect() as conn:
            result = conn.execute(text("SELECT version()"))
            version = result.scalar()
            print("✓ Connected successfully")
            print(f"  PostgreSQL version: {version}")
        return True
    except Exception as e:
        print(f"✗ Connection failed: {e}")
        return False


def create_tables(url: str) -> None:
    """Create all required database tables using SQLAlchemy metadata.

    Args:
        url: PostgreSQL connection URL.

    Returns:
        None.
    """
    try:
        from sqlalchemy import create_engine

        # Import the models to register them with Base
        sys.path.insert(0, ".")
        from core.storage.models import Base

        engine = create_engine(url, echo=False)
        Base.metadata.create_all(engine)
        print("✓ Tables created/verified:")
        for table_name in Base.metadata.tables:
            print(f"  - {table_name}")
    except Exception as e:
        print(f"✗ Failed to create tables: {e}")
        sys.exit(1)


def generate_env(url: str, env_path: str = ".env") -> None:
    """Generate a .env file with PostgreSQL configuration.

    Args:
        url: PostgreSQL connection URL to embed in the config.
        env_path: Filesystem path for the generated .env file.

    Returns:
        None.
    """
    env_content = f"""# Skynet PostgreSQL Configuration
# Generated by scripts/setup_postgres.py

REMOTE_DB_URL={url}

# Worker configuration
WORKER_CONCURRENCY=2
WORKER_POLL_INTERVAL=2.0

# Logging
LOG_LEVEL=INFO

# LLM API Key (fill in your key)
# OPENAI_API_KEY=sk-your-key-here
"""
    with open(env_path, "w") as f:
        f.write(env_content)
    print(f"✓ Configuration written to {env_path}")
    print("  Start the server with: python main.py")


def main() -> None:
    """Parse CLI arguments and run the PostgreSQL setup workflow.

    Returns:
        None.
    """
    parser = argparse.ArgumentParser(
        description="Setup Skynet with a remote PostgreSQL database",
        formatter_class=argparse.RawDescriptionHelpFormatter,
        epilog="""
Examples:
  # Using a full URL:
  python scripts/setup_postgres.py --url postgresql://user:pass@db.example.com:5432/skynet

  # Using individual parameters:
  python scripts/setup_postgres.py --host db.example.com --user skynet_user --password secret --dbname skynet

  # Supabase:
  python scripts/setup_postgres.py --url postgresql://postgres.xxx:password@aws-0-region.pooler.supabase.com:5432/postgres

  # Just test connection (no table creation):
  python scripts/setup_postgres.py --url postgresql://... --test-only

  # Write to a custom env file:
  python scripts/setup_postgres.py --url postgresql://... --env-file .env.production
        """,
    )
    parser.add_argument("--url", help="Full PostgreSQL connection URL")
    parser.add_argument("--host", help="Database host")
    parser.add_argument("--port", type=int, default=5432, help="Database port (default: 5432)")
    parser.add_argument("--user", help="Database username")
    parser.add_argument("--password", help="Database password")
    parser.add_argument("--dbname", help="Database name")
    parser.add_argument("--test-only", action="store_true", help="Only test connection, don't create tables")
    parser.add_argument("--env-file", default=".env", help="Path to .env file to generate (default: .env)")
    parser.add_argument("--skip-env", action="store_true", help="Don't generate .env file")

    args = parser.parse_args()

    if not args.url and not args.host:
        parser.print_help()
        sys.exit(1)

    url = build_url(args)
    masked_url = url.split("@")[-1] if "@" in url else url
    print("\n🔧 Skynet PostgreSQL Setup")
    print(f"   Target: {masked_url}\n")

    if not test_connection(url):
        sys.exit(1)

    if args.test_only:
        print("\n✓ Connection test passed (--test-only, skipping table creation)")
        return

    print()
    create_tables(url)

    if not args.skip_env:
        print()
        generate_env(url, args.env_file)

    print("\n✓ Setup complete! Start the server:")
    print("  python main.py")


if __name__ == "__main__":
    main()
