// Generated by scripts/split_messages.py. Do not edit by hand.
//
// Hebrew UI strings owned by the auth feature slice.

export const authMessages = {
  "auth.login.error": "שגיאה בהתחברות",
  "auth.login.loading": "מתחבר...",
  "auth.login.tagline": "מערכת אופטימיזציית פרומפטים",
  "auth.login.form_aria": "טופס התחברות",
  "auth.login.username": "שם משתמש",
  "auth.login.username_placeholder": "הזן שם משתמש",
  "auth.login.submit": "התחבר",
  "auth.login.meta_description": "התחבר למערכת Skynet לאופטימיזציית פרומפטים",
  "auto.auth.literal.1": "שם משתמש",
} as const;
