// Generated by scripts/split_messages.py. Do not edit by hand.
//
// Hebrew UI strings owned by the tutorial feature slice.

export const tutorialMessages = {
  "auto.features.tutorial.components.tutorial.menu.1": "מדריך Skynet",
  "auto.features.tutorial.components.tutorial.menu.2": 
    "סיור מודרך שמכסה כל פינה באפליקציה. נווט אתכם דרך לוח הבקרה, טופס ההגשה ודף התוצאות.",
  "auto.features.tutorial.components.tutorial.menu.3": "התחל מדריך",
  "auto.features.tutorial.components.tutorial.popover.1": " מתוך ",
  "auto.features.tutorial.components.tutorial.popover.2": "הקודם",
  "auto.features.tutorial.lib.steps.literal.1": "השירות היה מעולה, ממליץ בחום!",
  "auto.features.tutorial.lib.steps.literal.2": "המוצר הגיע שבור, מאוד מאכזב",
  "auto.features.tutorial.lib.steps.literal.3": "משלוח מהיר, אריזה טובה",
  "auto.features.tutorial.lib.steps.literal.4": "לא שווה את המחיר, איכות נמוכה",
  "auto.features.tutorial.lib.steps.literal.5": "חוויית קנייה נעימה, אחזור שוב",
  "auto.features.tutorial.lib.steps.literal.6": "נתונים מרכזיים",
  "auto.features.tutorial.lib.steps.literal.7": 
    "ארבע כרטיסיות שמסכמות את כל הפעילות: סה״כ ריצות, ריצות פעילות כרגע, ריצות שהצליחו וריצות שנכשלו — לצד אחוז ההצלחה/כישלון מתוך הסך הכולל.",
  "auto.features.tutorial.lib.steps.literal.8": "סרגל צד",
  "auto.features.tutorial.lib.steps.literal.9": "סטטיסטיקות",
  "auto.features.tutorial.lib.steps.literal.10": 
    "סמנו שתי ריצות או יותר שהושלמו בטבלה — סרגל פעולות יופיע בתחתית עם כפתור השוואה. לחיצה עליו פותחת את דף ההשוואה המפורט.",
  "auto.features.tutorial.lib.steps.literal.11": "השוואת הגדרות",
  "auto.features.tutorial.lib.steps.literal.12": "השוואת פרומפטים",
  "auto.features.tutorial.lib.steps.literal.13": "טופס הגשה",
  "auto.features.tutorial.lib.steps.literal.14": "פרטים בסיסיים",
  "auto.features.tutorial.lib.steps.literal.15": "מיפוי עמודות",
  "auto.features.tutorial.lib.steps.literal.16": "חלוקת נתונים",
  "auto.features.tutorial.lib.steps.literal.17": "רמת חיפוש",
  "auto.features.tutorial.lib.steps.literal.18": 
    "קלה: מהירה, מעט ניסיונות. בינונית: מאוזנת בין מהירות לאיכות. מעמיקה: יסודית, הרבה ניסיונות. ככל שרמת החיפוש גבוהה יותר, הריצה לוקחת יותר זמן אבל הסיכוי לשיפור משמעותי גדל.",
  "auto.features.tutorial.lib.steps.literal.19": "פרמטרי GEPA",
  "auto.features.tutorial.lib.steps.literal.20": "פרומפט התחלתי",
  "auto.features.tutorial.lib.steps.literal.21": "סקירה",
  "auto.features.tutorial.lib.steps.literal.22": "דף תוצאות",
  "auto.features.tutorial.lib.steps.literal.23": "שלבי התהליך",
  "auto.features.tutorial.lib.steps.literal.24": "לשונית נתונים",
  "auto.features.tutorial.lib.steps.literal.25": "שימוש",
  "auto.features.tutorial.lib.steps.literal.26": "לוגים",
  "auto.features.tutorial.lib.steps.literal.27": "הגדרות הריצה",
  "auto.features.tutorial.lib.steps.literal.28": "תיוג טקסטים",
  "auto.features.tutorial.lib.steps.literal.29": "טופס הגדרת תיוג",
  "auto.features.tutorial.lib.steps.literal.30": 
    "שלושה שלבים: בחירת קובץ ועמודת טקסט, בחירת מצב תיוג, והגדרת השאלה או הקטגוריות. אחרי ההגדרה מתחיל התיוג עם ניווט בחיצי מקלדת, קיצורי מקשים, וייצוא בלחיצה.",
  "auto.features.tutorial.lib.steps.literal.31": "מצבי תיוג",
  "auto.features.tutorial.lib.steps.literal.32": 
    "סיווג בינארי: שאלה עם כן/לא — מתאים לסינון או זיהוי סנטימנט. קטגוריות: בחירה מרשימה שתגדירו — אפשר לבחור יותר מאחת. טקסט חופשי: כתיבת תגובה לכל שורה — מתאים לחילוץ מידע או תרגום.",
  "auto.features.tutorial.lib.steps.literal.33": "זהו!",
  "auto.features.tutorial.lib.steps.literal.34": "מדריך",
  "auto.features.tutorial.lib.steps.literal.35": "הכירו כל פינה באפליקציה",
  "auto.features.tutorial.lib.steps.literal.36": "בדיקת מודלים",
  "auto.features.tutorial.lib.steps.literal.37": 
    "לפני שמתחילים ריצה, לחצו על הכפתור כדי לוודא שהמודל זמין ולמדוד זמן תגובה. הבדיקה מזהה בעיות קישוריות או הגדרה שגויה לפני שמשקיעים זמן בריצה ארוכה.",
  "auto.features.tutorial.lib.steps.literal.38": "גלריה ציבורית",
  "auto.features.tutorial.lib.steps.literal.39": 
    "מפת פיזור אינטראקטיבית של ריצות ציבוריות. סננו לפי מודלים, אופטימייזרים ומשימות, וגלו רעיונות לקונפיגורציות מצליחות לפני שמתחילים ריצה משלכם.",
  "auto.features.tutorial.lib.steps.literal.40": "API ואינטגרציה",
  "auto.features.tutorial.lib.steps.literal.41": 
    "מעבר לבדיקה בדפדפן, הפרומפט המאופטם זמין מיידית כ-REST API. העתיקו את כתובת ה-endpoint או השתמשו בקטעי הקוד המוכנים (Python, JavaScript, cURL) כדי לשלב את האופטימיזציה בקוד הייצור שלכם.",
  "auto.features.tutorial.lib.steps.literal.42": "סוכן AI",
  "auto.features.tutorial.lib.steps.literal.43": 
    "הכפתור הצף בפינה הוא נקודת הכניסה לסוכן AI. לחצו עליו כדי לפתוח צ'אט עם סוכן שמכיר את האפליקציה ויכול לעזור למלא את הוויזרד, להסביר תוצאות ולענות על שאלות.",
  "auto.features.tutorial.lib.steps.literal.44": "צ'אט עם הסוכן",
  "auto.features.tutorial.lib.steps.literal.45": 
    "פאנל הצ'אט מאפשר לדבר עם הסוכן ולבקש ממנו לבצע פעולות. בכותרת מופיע מצב אמון (Trust Mode) — בחרו אם הסוכן יבקש אישור לפני כל פעולה או יבצע אוטומטית. הסוכן רואה את מצב הוויזרד הנוכחי ויכול למלא שדות בעצמו.",
  "auto.features.tutorial.lib.demo.data.literal.1": "סיווג אימיילים",
  "auto.features.tutorial.lib.demo.data.literal.2": "Starting optimization: סיווג אימיילים",
  "auto.features.tutorial.lib.demo.data.literal.3": "Starting optimization: סיווג אימיילים",
  "auto.features.tutorial.lib.demo.data.literal.4": "Starting optimization: סיווג אימיילים",
  "auto.features.tutorial.lib.demo.data.literal.5": "Starting optimization: סיווג אימיילים",
  "auto.features.tutorial.lib.demo.data.literal.6": "Starting optimization: סיווג אימיילים",
  "auto.features.tutorial.lib.demo.data.literal.7": "סיווג אימיילים",
  "auto.features.tutorial.lib.demo.data.literal.8": 
    "סיווג אימיילים לקטגוריות: spam, important, promotional",
  "auto.features.tutorial.lib.demo.data.literal.9": "ניתוח סנטימנט",
  "auto.features.tutorial.lib.demo.data.literal.10": "זיהוי טון חיובי/שלילי בביקורות מוצרים",
  "auto.features.tutorial.lib.demo.data.literal.11": "סיכום טקסטים",
  "auto.features.tutorial.lib.demo.data.literal.12": "חילוץ ישויות",
  "auto.features.tutorial.lib.demo.data.literal.13": "זיהוי שמות וארגונים בטקסט חופשי",
  "auto.features.tutorial.lib.demo.data.literal.14": "תרגום עברית-אנגלית",
  "auto.features.tutorial.lib.demo.data.literal.15": "תרגום משפטים קצרים",
  "auto.features.tutorial.lib.demo.data.literal.16": "סיווג אימיילים",
  "auto.features.tutorial.lib.demo.data.literal.17": "סיכום טקסטים",
  "auto.features.tutorial.lib.demo.data.literal.18": "GEPA עם מודול Predict (ללא reasoning)",
  "auto.features.tutorial.components.tutorial.menu.literal.1": "סגור",
  "auto.features.tutorial.components.tutorial.popover.literal.1": "השהה",
  "auto.features.tutorial.components.tutorial.popover.literal.2": "נגן אוטומטי",
  "auto.features.tutorial.components.tutorial.popover.literal.3": "השהה",
  "auto.features.tutorial.components.tutorial.popover.literal.4": "נגן אוטומטי",
  "auto.features.tutorial.components.tutorial.popover.literal.5": "סגור מדריך",
  "auto.features.tutorial.components.tutorial.popover.literal.6": "סיום",
  "auto.features.tutorial.components.tutorial.popover.literal.7": "הבא",
  "auto.features.tutorial.lib.demo.data.template.1": 
    "{p1} לסיווג אימיילים לקטגוריות: spam, important, promotional",
  "auto.features.tutorial.lib.demo.data.template.2": 
    "סריקת {p1}: ארבעה {p2} {p3}/{p4} על אותה {p5}",
  "auto.features.tutorial.lib.demo.data.template.3": 
    "סריקת {p1}: ארבעה {p2} {p3}/{p4} על אותה {p5}",
  "auto.features.tutorial.lib.demo.data.template.4": "GEPA עם {p1} קל ומהיר",
  "auto.features.tutorial.lib.demo.data.template.5": "GEPA עם {p1} מתקדם",
  "auto.features.tutorial.lib.steps.template.1": "טבלת {p1}",
  "auto.features.tutorial.lib.steps.template.2": 
    "פירוט על כל הריצות. לחצו על כותרת עמודה למיון, על הפילטר לסינון, וגררו קצוות לשינוי רוחב. לחצו על פרטים כדי לפתוח את הפירוט על ה{p1}.",
  "auto.features.tutorial.lib.steps.template.3": 
    "למעלה: ניווט ללוח בקרה, הגשת {p1} חדשה ותיוג טקסטים. למטה: חיפוש חופשי והיסטוריית ריצות לפי תאריך. לחצו ⋯ ליד {p2} לשיתוף, שינוי שם, שכפול, הצמדה או מחיקה.",
  "auto.features.tutorial.lib.steps.template.4": 
    "גרפים אינטראקטיביים שמציגים {p1}, יעילות, השוואת {p2} וטבלת שיאים. לחצו על עמודה בגרף כדי לסנן {p3} ספציפית.",
  "auto.features.tutorial.lib.steps.template.5": "איך להשוות {p1}",
  "auto.features.tutorial.lib.steps.template.6": "השוואת {p1}",
  "auto.features.tutorial.lib.steps.template.7": 
    "למעלה רואים את הזוכה — הריצה עם ה{p1} הגבוה ביותר, יחד עם אחוז השיפור, משך הריצה וה{p2} שבו השתמשה.",
  "auto.features.tutorial.lib.steps.template.8": "השוואת {p1}",
  "auto.features.tutorial.lib.steps.template.9": 
    "גרף עמודות וטבלה שמציגים את {p1} מול ה{p2} לכל ריצה.",
  "auto.features.tutorial.lib.steps.template.10": 
    "לשונית 'הגדרות' מראה איזה {p1}, {p2}, {p3} וגודל {p4} שימשו בכל ריצה.",
  "auto.features.tutorial.lib.steps.template.11": 
    "לשונית 'פרומפטים' מראה את ההוראות המאופטמות וה{p1} שכל ריצה ייצרה, זה לצד זה. ככה אפשר להבין בדיוק איך שינוי ב{p2} או בהגדרות השפיע על הפרומפט הסופי.",
  "auto.features.tutorial.lib.steps.template.12": "השוואת {p1}",
  "auto.features.tutorial.lib.steps.template.13": 
    "לשונית '{p1}' עוברת דוגמה-דוגמה ומראה איך כל ריצה ענתה עליה ומה ה{p2} שקיבלה. אפשר לסנן רק {p3} שבהן יש חוסר הסכמה בין הריצות — ככה קל לאתר בדיוק איפה הן נבדלות.",
  "auto.features.tutorial.lib.steps.template.14": 
    "שישה שלבים: פרטים בסיסיים, {p1}, פרמטרים, קוד, {p2}, סיכום ושליחה.",
  "auto.features.tutorial.lib.steps.template.15": 
    "בשלב הראשון בוחרים שם, תיאור, וסוג {p1} ({p2} או {p3} שמשווה כמה הגדרות במקביל).",
  "auto.features.tutorial.lib.steps.template.16": "העלאת {p1}",
  "auto.features.tutorial.lib.steps.template.17": 
    "גררו קובץ CSV, JSON או Excel לאזור ההעלאה. כל שורה היא דוגמה אחת שהמערכת תלמד ממנה. ככל שיש יותר {p1} איכותיות, ה{p2} תהיה טובה יותר.",
  "auto.features.tutorial.lib.steps.template.18": 
    "סמנו כל עמודה כקלט (נשלח ל{p1}), פלט (התשובה הרצויה שלפיה מודדים הצלחה), או התעלם. המיפוי הזה מגדיר את הפרומפט ההתחלתי אוטומטית.",
  "auto.features.tutorial.lib.steps.template.19": 
    "Predict שולח את הקלט ישירות ל{p1} ומקבל תשובה. Chain of Thought מוסיף שדה reasoning לפני הפלט, שמאלץ את ה{p2} לנמק את התשובה צעד אחר צעד לפני שהוא מחזיר תוצאה.",
  "auto.features.tutorial.lib.steps.template.20": 
    "{p1}: ה{p2} לומד מה{p3} האלו. {p4}: בדיקה שהשיפור מתקיים גם על {p5} שלא שימשו לאימון. {p6}: הערכה סופית על {p7} שה{p8} מעולם לא ראה.",
  "auto.features.tutorial.lib.steps.template.21": 
    "גודל מדגם לרפלקציה: כמה {p1} ה{p2} מנתח בכל סבב כדי לזהות שגיאות. מקסימום סבבי הערכה: נקבע לפי רמת החיפוש, אפשר לכבות את הרמה באמצעות לחיצה על הרמה הנוכחית ולהגדיר ידנית. מיזוג מועמדים: משלב הוראות מכמה מועמדים טובים לפרומפט אחד משופר.",
  "auto.features.tutorial.lib.steps.template.22": 
    "הפרומפט ההתחלתי מגדיר מה ה{p1} מקבל ומה הוא צריך להחזיר. הוא נוצר אוטומטית ממיפוי העמודות, אבל חשוב לערוך אותו ולהוסיף תיאורים מדויקים לכל שדה כדי שהוא יהיה איכותי.",
  "auto.features.tutorial.lib.steps.template.23": 
    "פונקציה שמחזירה {p1} בין 0 ל-1 לכל תשובה. זו ההגדרה של מה נחשב ״תשובה טובה״, וה{p2} ינסה למקסם את ה{p3} הזה לאורך כל הריצה.",
  "auto.features.tutorial.lib.steps.template.24": "בחירת {p1}",
  "auto.features.tutorial.lib.steps.template.25": 
    "{p1} מייצר את התשובות. {p2} מנתח שגיאות ומציע שיפורים לפרומפט. אפשר לבחור {p3} שונים לכל תפקיד.",
  "auto.features.tutorial.lib.steps.template.26": 
    "סיכום כל ההגדרות בחמש לשוניות: כללי, {p1}, {p2}, {p3} וקוד. בדקו שהכל נכון לפני שליחה.",
  "auto.features.tutorial.lib.steps.template.27": "שליחת {p1}",
  "auto.features.tutorial.lib.steps.template.28": 
    "הכפתור שמפעיל את הכל. ברגע שלוחצים, המערכת מתחילה: מאמתת את הקלט, מחלקת את הנתונים, מריצה {p1}, ואז מפעילה את ה{p2}. אפשר לעקוב אחרי ההתקדמות בזמן אמת מדף התוצאות.",
  "auto.features.tutorial.lib.steps.template.29": 
    "אחרי שליחת {p1} מגיעים לדף התוצאות. בראש הדף: שם ה{p2}, תיאור, סטטוס הריצה וזמן שעבר. כפתור שכפול יוצר {p3} חדשה עם אותן הגדרות. בזמן ריצה פעילה מוצג כפתור ביטול, ולאחר סיום או כישלון — כפתור מחיקה.",
  "auto.features.tutorial.lib.steps.template.30": 
    "כל {p1} עוברת חמישה שלבים: אימות הקלט, חלוקת הנתונים, ריצת {p2} (לפני {p3}), ה{p4} עצמה, והערכה סופית. כל שלב מתעדכן בזמן אמת.",
  "auto.features.tutorial.lib.steps.template.31": "כרטיסי {p1}",
  "auto.features.tutorial.lib.steps.template.32": 
    "שלושה כרטיסים: {p1} (לפני {p2}), {p3} (אחרי), ואחוז השיפור ביניהם.",
  "auto.features.tutorial.lib.steps.template.33": "גרף {p1}",
  "auto.features.tutorial.lib.steps.template.34": 
    "עוקב אחרי ה{p1} לאורך כל הניסיונות של ה{p2}. רואים בדיוק מתי נמצא שילוב טוב יותר ואיך ה{p3} השתנה לאורך הריצה.",
  "auto.features.tutorial.lib.steps.template.35": 
    "כל דוגמה מה{p1} עם {p2} בצבע (ירוק = גבוה, אדום = נמוך), תחזית ה{p3}, והחלוקה ל{p4}, {p5} ו{p6}. אפשר למיין לפי {p7} כדי לזהות דפוסים.",
  "auto.features.tutorial.lib.steps.template.36": 
    "אחרי שהריצה מסתיימת, אפשר לבדוק את הפרומפט המאופטם בזמן אמת. הזינו קלט חדש וקבלו תשובה מיידית מה{p1} עם הפרומפט המשופר.",
  "auto.features.tutorial.lib.steps.template.37": 
    "לוגים בזמן אמת מה{p1}. מתעדכנים אוטומטית בזמן שהריצה פעילה. אפשר לסנן לפי רמה (info, warning, error ועוד), לפי שם ה-logger או pair_index, לחפש בטקסט חופשי ולמיין לפי זמן.",
  "auto.features.tutorial.lib.steps.template.38": 
    "כל ההגדרות של הריצה במקום אחד: {p1}, פרמטרים וחלוקת נתונים.",
  "auto.features.tutorial.lib.steps.template.39": "סריקת {p1} (Grid Search)",
  "auto.features.tutorial.lib.steps.template.40": 
    "במקום ריצה של {p1} יחיד, סריקה משווה כמה {p2} של {p3} × {p4} על אותה {p5}. כל שורה היא {p6}: מימין {p7} האיכות, ובאמצע זמן התגובה הממוצע. הזוכה הוא בעל ציון האיכות הגבוה ביותר ומסומן בכתר.",
  "auto.features.tutorial.lib.steps.template.41": "פרטי {p1} {p2}",
  "auto.features.tutorial.lib.steps.template.42": 
    "לחיצה על {p1} פותחת תצוגה מפורטת: {p2} לפני/אחרי, ה{p3} ב{p4}, משך הריצה, מספר הקריאות ל{p5} וגרף התקדמות.",
  "auto.features.tutorial.lib.steps.template.43": 
    "כלי לתיוג {p1}ים ישירות באפליקציה. העלו קובץ CSV, JSON או Excel, בחרו מצב תיוג, ותייגו שורה אחרי שורה. בסיום אפשר לייצא את התוצאות בכל הפורמטים.",
  "auto.features.tutorial.lib.steps.template.44": 
    "עכשיו אתם מכירים את כל מה ש-Skynet מציע. הגישו {p1} ראשונה, עקבו אחרי ה{p2} בזמן אמת, ובדקו את הפרומפט המשופר בלשונית שימוש.",
} as const;
