// Generated by scripts/split_messages.py. Do not edit by hand.
//
// Hebrew UI strings owned by the optimizations feature slice.

export const optimizationsMessages = {
  "optimization.cancel.sent": "בקשת ביטול נשלחה",
  "optimization.cancel.failed": "ביטול נכשל",
  "optimization.delete.failed": "מחיקה נכשלה",
  "optimization.file.parse_error": "שגיאה בפענוח הקובץ",
} as const;
