{{- if .Values.backend.podDisruptionBudget.enabled }}
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: {{ include "skynet.backend.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "skynet.labels" . | nindent 4 }}
    app.kubernetes.io/component: backend
spec:
  minAvailable: {{ .Values.backend.podDisruptionBudget.minAvailable }}
  selector:
    matchLabels:
      {{- include "skynet.backend.selectorLabels" . | nindent 6 }}
{{- end }}
