{{- if .Values.pgbouncer.enabled }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "skynet.pgbouncer.fullname" . }}-config
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "skynet.labels" . | nindent 4 }}
    app.kubernetes.io/component: pgbouncer
data:
  pgbouncer.ini: |
    [databases]
    {{ include "skynet.dbName" . }} = host={{ include "skynet.dbHost" . }} port={{ include "skynet.dbPort" . }} dbname={{ include "skynet.dbName" . }}

    [pgbouncer]
    listen_addr = 0.0.0.0
    listen_port = {{ .Values.pgbouncer.service.port }}
    auth_type = plain
    auth_file = /etc/pgbouncer-generated/userlist.txt
    pool_mode = transaction
    default_pool_size = {{ .Values.pgbouncer.defaultPoolSize }}
    max_client_conn = {{ .Values.pgbouncer.maxClientConn }}
    server_tls_sslmode = {{ if .Values.externalDatabase.enabled }}require{{ else }}disable{{ end }}
    ignore_startup_parameters = extra_float_digits,options
    server_reset_query =
    admin_users = {{ include "skynet.dbUser" . }}
    stats_users = {{ include "skynet.dbUser" . }}
{{- end }}
