{{- if .Values.openshift.routes.enabled }}
apiVersion: route.openshift.io/v1
kind: Route
metadata:
  name: {{ include "skynet.backend.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "skynet.labels" . | nindent 4 }}
    app.kubernetes.io/component: backend
  annotations:
    {{- with .Values.openshift.routes.backend.annotations }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
spec:
  {{- with .Values.openshift.routes.backend.host }}
  host: {{ . }}
  {{- end }}
  to:
    kind: Service
    name: {{ include "skynet.backend.fullname" . }}
    weight: 100
  port:
    targetPort: http
  {{- include "skynet.route.tls" .Values.openshift.routes.backend.tls | nindent 2 }}
  wildcardPolicy: None
{{- end }}
