"""baseline

Revision ID: 342f7449be26
Revises: 
Create Date: 2026-05-02 12:39:17.013087

"""
from __future__ import annotations

from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision: str = '342f7449be26'
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('job_embeddings',
    sa.Column('optimization_id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=255), nullable=True),
    sa.Column('optimization_type', sa.String(length=32), nullable=True),
    sa.Column('winning_model', sa.String(length=255), nullable=True),
    sa.Column('winning_rank', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('embedding_summary', pgvector.sqlalchemy.vector.VECTOR(dim=512), nullable=True),
    sa.Column('embedding_code', pgvector.sqlalchemy.vector.VECTOR(dim=512), nullable=True),
    sa.Column('embedding_schema', pgvector.sqlalchemy.vector.VECTOR(dim=512), nullable=True),
    sa.Column('is_recommendable', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('baseline_metric', sa.Float(), nullable=True),
    sa.Column('optimized_metric', sa.Float(), nullable=True),
    sa.Column('summary_text', sa.Text(), nullable=True),
    sa.Column('signature_code', sa.Text(), nullable=True),
    sa.Column('metric_name', sa.String(length=255), nullable=True),
    sa.Column('optimizer_name', sa.String(length=64), nullable=True),
    sa.Column('optimizer_kwargs', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=True),
    sa.Column('module_name', sa.String(length=128), nullable=True),
    sa.Column('task_name', sa.String(length=255), nullable=True),
    sa.Column('projection_x', sa.Float(), nullable=True),
    sa.Column('projection_y', sa.Float(), nullable=True),
    sa.PrimaryKeyConstraint('optimization_id')
    )
    op.create_index(op.f('ix_job_embeddings_is_recommendable'), 'job_embeddings', ['is_recommendable'], unique=False)
    op.create_index(op.f('ix_job_embeddings_optimization_type'), 'job_embeddings', ['optimization_type'], unique=False)
    op.create_index(op.f('ix_job_embeddings_user_id'), 'job_embeddings', ['user_id'], unique=False)
    op.create_table('job_logs',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('optimization_id', sa.String(length=36), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.Column('level', sa.String(length=20), nullable=False),
    sa.Column('logger', sa.String(length=255), nullable=False),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('pair_index', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_job_logs_optimization_id'), 'job_logs', ['optimization_id'], unique=False)
    op.create_table('job_progress_events',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('optimization_id', sa.String(length=36), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.Column('event', sa.String(length=255), nullable=True),
    sa.Column('metrics', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_job_progress_events_optimization_id'), 'job_progress_events', ['optimization_id'], unique=False)
    op.create_index('ix_job_progress_events_optimization_timestamp', 'job_progress_events', ['optimization_id', 'timestamp'], unique=False)
    op.create_table('job_templates',
    sa.Column('template_id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('username', sa.String(length=255), nullable=False),
    sa.Column('config', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('template_id')
    )
    op.create_table('jobs',
    sa.Column('optimization_id', sa.String(length=36), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('started_at', sa.DateTime(), nullable=True),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.Column('estimated_remaining_seconds', sa.Float(), nullable=True),
    sa.Column('message', sa.Text(), nullable=True),
    sa.Column('latest_metrics', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('result', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=True),
    sa.Column('payload_overview', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('payload', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=True),
    sa.Column('username', sa.String(length=255), nullable=True),
    sa.Column('optimization_type', sa.String(length=64), nullable=True),
    sa.Column('claimed_by', sa.String(length=64), nullable=True),
    sa.Column('claimed_at', sa.DateTime(), nullable=True),
    sa.Column('lease_expires_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('optimization_id')
    )
    op.create_index(op.f('ix_jobs_created_at'), 'jobs', ['created_at'], unique=False)
    op.create_index('ix_jobs_lease_expires_at', 'jobs', ['lease_expires_at'], unique=False)
    op.create_index(op.f('ix_jobs_optimization_type'), 'jobs', ['optimization_type'], unique=False)
    op.create_index(op.f('ix_jobs_status'), 'jobs', ['status'], unique=False)
    op.create_index('ix_jobs_status_created_at', 'jobs', ['status', 'created_at'], unique=False)
    op.create_index(op.f('ix_jobs_username'), 'jobs', ['username'], unique=False)
    op.create_table('user_quota_audit_events',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('actor', sa.String(length=255), nullable=False),
    sa.Column('target_username', sa.String(length=255), nullable=False),
    sa.Column('action', sa.String(length=32), nullable=False),
    sa.Column('old_quota', sa.Integer(), nullable=True),
    sa.Column('new_quota', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_quota_audit_events_actor'), 'user_quota_audit_events', ['actor'], unique=False)
    op.create_index(op.f('ix_user_quota_audit_events_target_username'), 'user_quota_audit_events', ['target_username'], unique=False)
    op.create_table('user_quota_overrides',
    sa.Column('username', sa.String(length=255), nullable=False),
    sa.Column('quota', sa.Integer(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('updated_by', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('username')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user_quota_overrides')
    op.drop_index(op.f('ix_user_quota_audit_events_target_username'), table_name='user_quota_audit_events')
    op.drop_index(op.f('ix_user_quota_audit_events_actor'), table_name='user_quota_audit_events')
    op.drop_table('user_quota_audit_events')
    op.drop_index(op.f('ix_jobs_username'), table_name='jobs')
    op.drop_index('ix_jobs_status_created_at', table_name='jobs')
    op.drop_index(op.f('ix_jobs_status'), table_name='jobs')
    op.drop_index(op.f('ix_jobs_optimization_type'), table_name='jobs')
    op.drop_index('ix_jobs_lease_expires_at', table_name='jobs')
    op.drop_index(op.f('ix_jobs_created_at'), table_name='jobs')
    op.drop_table('jobs')
    op.drop_table('job_templates')
    op.drop_index('ix_job_progress_events_optimization_timestamp', table_name='job_progress_events')
    op.drop_index(op.f('ix_job_progress_events_optimization_id'), table_name='job_progress_events')
    op.drop_table('job_progress_events')
    op.drop_index(op.f('ix_job_logs_optimization_id'), table_name='job_logs')
    op.drop_table('job_logs')
    op.drop_index(op.f('ix_job_embeddings_user_id'), table_name='job_embeddings')
    op.drop_index(op.f('ix_job_embeddings_optimization_type'), table_name='job_embeddings')
    op.drop_index(op.f('ix_job_embeddings_is_recommendable'), table_name='job_embeddings')
    op.drop_table('job_embeddings')
    # ### end Alembic commands ###
