// Generated by scripts/split_messages.py. Do not edit by hand.
//
// Hebrew UI strings owned by the compare feature slice.

import { TERMS } from "@/shared/lib/terms";

export const compareMessages = {
  "compare.select_two": `בחר שתי ${TERMS.optimizationPlural} מלוח הבקרה כדי להשוות ביניהן`,
  "compare.load_error": `שגיאה בטעינת ה${TERMS.optimizationPlural}`,
  "compare.mismatch": `להשוואה דרושים אותו ${TERMS.dataset}, אותה ${TERMS.metric} ואותו ${TERMS.signature} — הריצה שנבחרה שונה`,
  "compare.cap_reached": `ניתן להשוות עד 8 ${TERMS.optimizationPlural} בבת אחת`,
  "compare.partial_load": "חלק מהריצות לא נטענו והושמטו מההשוואה",
} as const;
