"""Generate typed i18n constants from the shared catalog.

The source of truth is ``i18n/locales/he.json``. This script emits:

* ``frontend/src/shared/lib/generated/i18n-catalog.ts`` for TypeScript callers.
* ``backend/core/i18n_keys.py`` for Python callers.

It intentionally does not extract or translate copy. It only turns the shared
catalog into stable, typo-resistant constants for both runtimes.
"""

from __future__ import annotations

import json
import re
from pathlib import Path
from typing import Any

ROOT = Path(__file__).resolve().parents[1]
CATALOG_PATH = ROOT / "i18n" / "locales" / "he.json"
TS_OUT = ROOT / "frontend" / "src" / "shared" / "lib" / "generated" / "i18n-catalog.ts"
PY_OUT = ROOT / "backend" / "core" / "i18n_keys.py"
KEYS_OUT = ROOT / "i18n" / "keys.json"


def _load_catalog() -> dict[str, Any]:
    catalog = json.loads(CATALOG_PATH.read_text(encoding="utf-8"))
    for section in ("terms", "messages"):
        if not isinstance(catalog.get(section), dict):
            raise ValueError(f"{CATALOG_PATH} must contain object section {section!r}")
    return catalog


def _enum_name(key: str) -> str:
    key = re.sub(r"([a-z0-9])([A-Z])", r"\1_\2", key)
    name = re.sub(r"[^0-9A-Za-z]+", "_", key).strip("_").upper()
    return name or "KEY"


def _ts_object(values: dict[str, str]) -> str:
    lines = ["{"]
    for key, value in values.items():
        prop = key if re.fullmatch(r"[A-Za-z_$][0-9A-Za-z_$]*", key) else json.dumps(key)
        lines.append(f"  {prop}: {json.dumps(value, ensure_ascii=False)},")
    lines.append("}")
    return "\n".join(lines)


def _write_ts(catalog: dict[str, Any]) -> None:
    terms_ts = _ts_object(catalog["terms"])
    messages_ts = _ts_object(catalog["messages"])
    message_key_ts = _ts_object({_enum_name(key): key for key in sorted(catalog["messages"])})
    term_key_ts = _ts_object({_enum_name(key): key for key in sorted(catalog["terms"])})
    TS_OUT.parent.mkdir(parents=True, exist_ok=True)
    TS_OUT.write_text(
        "\n".join(
            [
                "// Generated by scripts/generate_i18n.py. Do not edit by hand.",
                "",
                f"export const TERMS = {terms_ts} as const;",
                "",
                f"export const I18N_MESSAGES = {messages_ts} as const;",
                "",
                "export type TermKey = keyof typeof TERMS;",
                "export type I18nMessageKey = keyof typeof I18N_MESSAGES;",
                "",
                f"export const I18N_KEY = {message_key_ts} as const;",
                "",
                f"export const TERM_KEY = {term_key_ts} as const;",
                "",
            ]
        ),
        encoding="utf-8",
    )


def _write_py(catalog: dict[str, Any]) -> None:
    message_lines = [f"    {_enum_name(key)} = {key!r}" for key in sorted(catalog["messages"])]
    term_lines = [f"    {_enum_name(key)} = {key!r}" for key in sorted(catalog["terms"])]
    PY_OUT.write_text(
        "\n".join(
            [
                '"""Generated i18n key constants. Do not edit by hand."""',
                "",
                "from __future__ import annotations",
                "",
                "from enum import Enum",
                "",
                "",
                "class I18nKey(str, Enum):",
                *message_lines,
                "",
                "",
                "class TermKey(str, Enum):",
                *term_lines,
                "",
            ]
        ),
        encoding="utf-8",
    )


def _write_keys(catalog: dict[str, Any]) -> None:
    KEYS_OUT.write_text(
        json.dumps(
            {
                "messages": sorted(catalog["messages"]),
                "terms": sorted(catalog["terms"]),
            },
            ensure_ascii=False,
            indent=2,
        )
        + "\n",
        encoding="utf-8",
    )


def main() -> None:
    catalog = _load_catalog()
    _write_ts(catalog)
    _write_py(catalog)
    _write_keys(catalog)


if __name__ == "__main__":
    main()
