// Generated by scripts/split_messages.py. Do not edit by hand.
//
// Hebrew UI strings owned by the explore feature slice.

import { TERMS } from "@/shared/lib/terms";

export const exploreMessages = {
  "explore.filter.all": "הכל",
  "explore.filter.run": TERMS.optimizationTypeRun,
  "explore.filter.grid": TERMS.optimizationTypeGrid,
  "explore.filter.aria": "סינון סוג ריצה",
  "explore.filter.showing": "מציג {count} מתוך {total}",
  "explore.filter.no_match": "אין ריצות מסוג זה.",
  "explore.filter.clear": "הצג הכל",
  "explore.empty.title": "השדה עדיין ריק. ריצות מופיעות כאן אחרי שמעבדים אותן.",
  "explore.empty.cta": "היה הראשון",
  "explore.detail.task": `ה${TERMS.task}`,
  "explore.detail.model": TERMS.winningModel,
  "explore.detail.optimizer": TERMS.optimizer,
  "explore.detail.score": TERMS.score,
  "explore.detail.time_ago": "לפני",
  "explore.detail.time.now": "רגע",
  "explore.detail.time.minutes": "{p1} דק׳",
  "explore.detail.time.hours": "{p1} שע׳",
  "explore.detail.time.days": "{p1} ימים",
  "explore.detail.close": "סגור",
  "explore.detail.module": "מודול",
  "explore.detail.open_action": "פתח",
  "explore.tooltip.open_hint": "לחצו לפרטים",
  "explore.map.reset": "איפוס תצוגה",
  "explore.canvas.aria_label": "מפת פיזור של {count} ריצות. השתמשו בעכבר או באצבע להזזה ולקירוב; לחיצה על נקודה פותחת את פרטי הריצה.",
} as const;
