// Generated by scripts/split_messages.py. Do not edit by hand.
//
// Hebrew UI strings owned by the explore feature slice.

import { TERMS } from "@/shared/lib/terms";

export const exploreMessages = {
  "explore.filter.all": "הכל",
  "explore.filter.run": TERMS.optimizationTypeRun,
  "explore.filter.grid": TERMS.optimizationTypeGrid,
  "explore.filter.aria": "סינון סוג ריצה",
  "explore.filter.showing": "מציג {count} מתוך {total}",
  "explore.filter.no_match": "אין ריצות מסוג זה.",
  "explore.filter.clear": "הצג הכל",
  "explore.empty.title": "השדה עדיין ריק. ריצות מופיעות כאן אחרי שמעבדים אותן.",
  "explore.empty.cta": "היה הראשון",
  "explore.detail.task": `ה${TERMS.task}`,
  "explore.detail.model": TERMS.winningModel,
  "explore.detail.optimizer": TERMS.optimizer,
  "explore.detail.score": TERMS.score,
  "explore.detail.time_ago": "לפני",
  "explore.cold_corpus": "השדה עוד קטן. כדאי לחזור אחרי כמה ריצות נוספות.",
  "explore.your_job.caption": "זו הריצה שלך.",
  "explore.detail.empty": "לחצו על נקודה כדי לראות פרטים.",
  "explore.tooltip.open_hint": "לחצו לפרטים",
  "explore.map.reset": "איפוס תצוגה",
  "auto.features.explore.components.exploredetailpanel.1": "פתח ",
  "auto.features.explore.components.exploredetailpanel.literal.1": "לפני רגע",
  "auto.features.explore.components.exploredetailpanel.literal.2": "סגור",
  "auto.features.explore.components.exploredetailpanel.literal.3": "מודול",
  "auto.features.explore.components.exploredetailpanel.template.1": "לפני {p1} דק׳",
  "auto.features.explore.components.exploredetailpanel.template.2": "לפני {p1} שע׳",
  "auto.features.explore.components.exploredetailpanel.template.3": "לפני {p1} ימים",
  "auto.features.explore.components.exploredetailpanel.template.4": "פתח {p1}",
} as const;
